export const pathname = {
  home: "/",
  about: "/about",
  contact: "/contact",
  developer: "/team",
  tourPlan: "/tourplan",
  booked: "/booked",
  cardDetails: "/cardDetails",
  cart: "/cart",
  hotel: "/hotel",
  flight: "/flight",
  payment: "/payment",
  confirmed: "/confirmed",
  login: "/login",
  signup: "/signup",
  forgotPassword: "/forgot-password",
  profile: "/profile",
  booking: "/booking",
  dashboardMain: "/dashboard/main"
}